name: usb_voice_receiver
description: Windows Desktop Receiver for USB Voice Typer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  tray_manager: ^0.2.3
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
